# Generated by Django 6.0.4 on 2026-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_email_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
