# Generated by Django 6.0.4 on 2026-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='test_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='test_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
    ]
